# Generated by Django 5.2.11 on 2026-02-09 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('flight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_type', models.CharField(choices=[('surveillance', 'Наблюдение'), ('mapping', 'Картографирование'), ('inspection', 'Инспекция'), ('delivery', 'Доставка'), ('training', 'Тренировка'), ('other', 'Другое')], max_length=20, verbose_name='Тип миссии')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('non-active', 'Неактивен'), ('unavailable', 'Недоступен')], default='non-active', max_length=20)),
                ('control_session_id', models.CharField(blank=True, max_length=100)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uav_name', models.CharField(max_length=100)),
                ('serial_num', models.CharField(max_length=50, unique=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('max_flight_time', models.IntegerField(blank=True, null=True)),
                ('max_range', models.IntegerField(blank=True, null=True)),
                ('max_speed', models.IntegerField(blank=True, null=True)),
                ('battery_capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Доступен'), ('in_use', 'В использовании'), ('maintenance', 'На обслуживании')], default='available', max_length=20)),
                ('is_connected', models.BooleanField(default=False)),
                ('connection_token', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ControlCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_type', models.CharField(choices=[('connect', 'Подключение'), ('disconnect', 'Отключение'), ('takeoff', 'Взлет'), ('land', 'Посадка'), ('move', 'Движение'), ('stop', 'Стоп'), ('rtl', 'Возврат'), ('emergency', 'Авария')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('executed', models.BooleanField(default=False)),
                ('result', models.TextField(blank=True)),
                ('direction', models.CharField(blank=True, choices=[('up', 'Вверх'), ('down', 'Вниз'), ('left', 'Влево'), ('right', 'Вправо'), ('up_left', 'Вверх-влево'), ('up_right', 'Вверх-вправо'), ('down_left', 'Вниз-влево'), ('down_right', 'Вниз-вправо')], max_length=20)),
                ('speed', models.FloatField(default=0.5)),
                ('duration', models.FloatField(default=1.0)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.flightstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_allowed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='pilot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pilot', verbose_name='Оператор'),
        ),
        migrations.CreateModel(
            name='Translating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_tr', models.FileField(upload_to='Flight_Vid')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.flightstatus')),
            ],
        ),
        migrations.CreateModel(
            name='PilotPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_control', models.BooleanField(default=False)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pilot')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uav')),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='allowed_uavs',
            field=models.ManyToManyField(through='app.PilotPermission', to='app.uav'),
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='drone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uav', verbose_name='БПЛА'),
        ),
    ]
